package com.lokaso.dao;

import android.database.sqlite.SQLiteDatabase;


import com.lokaso.dao.classes.InterestDao;
import com.lokaso.dao.classes.LocationDao;
import com.lokaso.dao.classes.OptionDao;
import com.lokaso.dao.classes.ProfessionDao;
import com.lokaso.model.Interest;
import com.lokaso.model.Option;
import com.lokaso.model.Place;
import com.lokaso.model.Profession;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    //MEMBERS ITEM
    private final DaoConfig optionDaoConfig;
    private final OptionDao optionDao;

    private final DaoConfig interestDaoConfig;
    private final InterestDao interestDao;

    private final DaoConfig professionDaoConfig;
    private final ProfessionDao professionDao;

    private final DaoConfig locationDaoConfig;
    private final LocationDao locationDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        //MEMBERS ITEM
        interestDaoConfig = daoConfigMap.get(InterestDao.class).clone();
        interestDaoConfig.initIdentityScope(type);
        interestDao = new InterestDao(interestDaoConfig, this);
        registerDao(Interest.class, interestDao);

        //MEMBERS ITEM
        professionDaoConfig = daoConfigMap.get(ProfessionDao.class).clone();
        professionDaoConfig.initIdentityScope(type);
        professionDao = new ProfessionDao(professionDaoConfig, this);
        registerDao(Profession.class, professionDao);

        //MEMBERS ITEM
        locationDaoConfig = daoConfigMap.get(LocationDao.class).clone();
        locationDaoConfig.initIdentityScope(type);
        locationDao = new LocationDao(locationDaoConfig, this);
        registerDao(Place.class, locationDao);

        //MEMBERS ITEM
        optionDaoConfig = daoConfigMap.get(OptionDao.class).clone();
        optionDaoConfig.initIdentityScope(type);
        optionDao = new OptionDao(optionDaoConfig, this);
        registerDao(Option.class, optionDao);

        //TODO ADD HERE

    }
    
    public void clear() {
        interestDaoConfig.getIdentityScope().clear();
        professionDaoConfig.getIdentityScope().clear();
        locationDaoConfig.getIdentityScope().clear();

        optionDaoConfig.getIdentityScope().clear();
    }

    public InterestDao getInterestDao() {
        return interestDao;
    }

    public ProfessionDao getProfessionDao() {
        return professionDao;
    }

    public LocationDao getLocationDao() {
        return locationDao;
    }


    public OptionDao getOptionDao() {
        return optionDao;
    }

}
